### PR TITLE
Add missing @Test annotation

### PR DESCRIPTION
**Pull request by BraisGabin**
Moving the code from Java6 to Java8 I found this test that doesn't have the `@Test` annotation. And, of course: the code that is not tested has bugs...

### CODE REVIEW

**Comment by JakeWharton** [comment]
This conflicts now after the 3.x merge. Please rebase. Also have these changes landed in RxJava itself?

**Comment by BraisGabin** [comment]
Rebased

> Also have these changes landed in RxJava itself?

I don't know what do you mean.

**Comment by JakeWharton** [comment]
This codebase mirrors the subject codebase inside RxJava.

**Comment by JakeWharton** [comment]
Or, put a different way, I didn't write any of this code. I just took all the subject code and pared it down. Thus, and changes like this should land in RxJava for its subject code before landing here so that they stay in sync.

**Comment by BraisGabin** [comment]
Got it! I'll check.

**Comment by BraisGabin** [comment]
Yeap, the annotation was missing in RxJava too: https://github.com/ReactiveX/RxJava/pull/6990

**Pull request merged**
