### PR TITLE
Fix accept nullability annotations

### PR DESCRIPTION
**Pull request by Jawnnypoo**
Follow up to https://github.com/JakeWharton/RxRelay/pull/48 which adds the annotation to all the subclasses

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
We are still using RxJava 2, are there plans to have RxRelay 2.x and 3.x for some amount of time?

**Comment by JakeWharton** [comment]
2 isn't going anywhere, but it's unlikely to see changes, and it hasn't for a very long time.

**Comment by Jawnnypoo** [comment]
Okay. Does this look good for 3.x?

**Comment by Jawnnypoo** [comment]
My Kotlin heart desires this PR being merged 😜

**Comment by Jawnnypoo** [comment]
@JakeWharton Don't want to be a bother, but I think this would be a nice improvement.

**Pull request merged**
