### PR TITLE
Fix truncation bugs in ReplayRelay following RxJava ReplaySubject fix.

### LINKED ISSUE #46: ReplayRelay NullPointerException
Apologies if my error, rx stack traces are hard to understand. We are getting an NPE using ReplayRelay. Attached is the stack trace.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.concurrent.atomic.AtomicReference.get()' on a null object reference
       at com.jakewharton.rxrelay2.ReplayRelay$SizeBoundReplayBuffer.replay(ReplayRelay.java:683)
       at com.jakewharton.rxrelay2.ReplayRelay.subscribeActual(ReplayRelay.java:221)
       at io.reactivex.Observable.subscribe(Observable.java:12090)
       at io.reactivex.internal.operators.observable.ObservableFilter.subscribeActual(ObservableFilter.java:30)
       at io.reactivex.Observable.subscribe(Observable.java:12090)
       at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
       at io.reactivex.Observable.subscribe(Observable.java:12090)
       at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.drain(ObservableConcatMap.java:475)
       at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.onSubscribe(ObservableConcatMap.java:330)
       at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(ObservableFromArray.java:31)
       at io.reactivex.Observable.subscribe(Observable.java:12090)
       at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:55)
       at io.reactivex.Observable.subscribe(Observable.java:12090)
       at io.reactivex.internal.operators.observable.ObservableCombineLatest$LatestCoordinator.subscribe(ObservableCombineLatest.java:117)
       at io.reactivex.internal.operators.observable.ObservableCombineLatest.subscribeActual(ObservableCombineLatest.java:71)
       at io.reactivex.Observable.subscribe(Observable.java:12090)
       at io.reactivex.internal.operators.observable.ObservableDistinctUntilChanged.subscribeActual(ObservableDistinctUntilChanged.java:35)
       at io.reactivex.Observable.subscribe(Observable.java:12090)
       at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:29)
       at io.reactivex.Flowable.subscribe(Flowable.java:14479)
       at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.subscribeActual(FlowableOnBackpressureLatest.java:32)
       at io.reactivex.Flowable.subscribe(Flowable.java:14479)
       at io.reactivex.Flowable.subscribe(Flowable.java:14426)
       at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

### PR DESCRIPTION
**Pull request by hujim**
Fixes https://github.com/JakeWharton/RxRelay/issues/46

Equivalent changes from
https://github.com/ReactiveX/RxJava/pull/6602

Some minor test changes regarding Subject vs Relay differences.

### CODE REVIEW

**Comment by hujim** [comment]
https://travis-ci.community/t/install-of-oracle-jdk8-is-failing/4365
It seems that travis.yml might require one of the suggested changes..

**Comment by JakeWharton** [comment]
Rebased and kicked CI

**Comment by JakeWharton** [comment]
Thanks!

**Comment by JakeWharton** [comment]
Released in 2.1.1. Thanks again!

**Pull request merged**
